username = "mauli123"
password = "m@uli123"
first_survey_name=" Goverment"
url = "https://www.surveymonkey.com/"
login_submit = "//form[@id='sign_in_form']//button[@type='submit']"
new_survey_title = "Central Goverment"
new_page_title = "New Page Title"
first_question = "Enter your email..?"
second_question = "From when you are using Survey Monkey.?"
third_question = "How often do you use SurveyMonkey?"
four_question = "How will rate the ease of survey creation?"
five_question = "Did you get meaningful data from survey analysis?"
six_question = "Check the Features you like about SurveyMonkey?"
seven_question = "Rate our features. (Matrix Rating Scale)"
eight_question = "List the features you like most."
nine_question = "Will recommend SurveyMonkey to your friends / Colleagues?"
ten_question = "Comments / Feedback (Text-area)"

