username = "mauli123"
password = "m@uli123"
first_survey_name=" Goverment"
url = "https://www.surveymonkey.com/"
login_submit = "//form[@id='sign_in_form']//button[@type='submit']"
new_survey_title = "Central Goverment"
new_page_title = "New Page Title"

first_question_enter = "Enter your email..?"
second_question_enter = "From when you are using Survey Monkey.?"
third_question_enter = "How often do you use SurveyMonkey?"
four_question_enter = "How will rate the ease of survey creation?"
five_question_enter = "Did you get meaningful data from survey analysis?"
six_question_enter = "Check the Features you like about SurveyMonkey?"
seven_question_enter = "Rate our features. (Matrix Rating Scale)"
eight_question_enter = "List the features you like most."
nine_question_enter = "Will recommend SurveyMonkey to your friends / Colleagues?"
ten_question_enter = "Comments / Feedback (Text-area)"

six_1 = "Question Bank"
six_2 = "Themes"
six_3 = "Graphical Result"
six_4 = "Template Re-usability"
six_5 = "Collectors"

seven_1 = "Service"
seven_2 = "Support"
seven_3 = "Responsive"
seven_4 = "Very Good"
seven_5 = "Good"
seven_6 = "Average"
seven_7 = "Below Average"


